-- 1. CLEANUP (Allows you to run the script multiple times)
DROP TABLE IF EXISTS public.inventory CASCADE;
DROP TABLE IF EXISTS public.account CASCADE;
DROP TABLE IF EXISTS public.classification CASCADE;
DROP TYPE IF EXISTS public.account_type;

-- 2. CREATE CUSTOM TYPES
CREATE TYPE public.account_type AS ENUM ('Client', 'Employee', 'Admin');

-- 3. CREATE TABLES
-- Classification Table
CREATE TABLE public.classification (
    classification_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    classification_name VARCHAR(30) NOT NULL
);

-- Inventory Table
CREATE TABLE public.inventory (
    inv_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inv_make VARCHAR(30) NOT NULL,
    inv_model VARCHAR(30) NOT NULL,
    inv_description TEXT,
    inv_image VARCHAR(50) NOT NULL,
    inv_thumbnail VARCHAR(50) NOT NULL,
    inv_price DECIMAL(10, 0) NOT NULL,
    inv_miles INT NOT NULL,
    inv_color VARCHAR(20) NOT NULL,
    classification_id INT NOT NULL,
    CONSTRAINT fk_classification FOREIGN KEY (classification_id) 
        REFERENCES public.classification (classification_id)
);

-- Account Table
CREATE TABLE public.account (
    account_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_firstname VARCHAR(50) NOT NULL,
    account_lastname VARCHAR(50) NOT NULL,
    account_email VARCHAR(100) UNIQUE NOT NULL,
    account_password TEXT NOT NULL,
    account_type public.account_type NOT NULL DEFAULT 'Client'
);

-- 4. SEED DATA (Important: Insert data before running updates)
-- [Note: You would typically include your INSERT statements here]

-- 5. FINAL TASK UPDATES (Queries 4 and 6 from Assignment 2)
-- Update Hummer Description
UPDATE public.inventory
SET inv_description = REPLACE(inv_description, 'small interiors', 'a huge interior')
WHERE inv_make = 'GM' AND inv_model = 'Hummer';

-- Update File Paths
UPDATE public.inventory
SET inv_image = REPLACE(inv_image, '/images/', '/images/vehicles/'),
    inv_thumbnail = REPLACE(inv_thumbnail, '/images/', '/images/vehicles/');